name: Render
on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Build, Push and Release a Docker container to Render.
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cf9iqk4gqg47p3vddgng?key=ZxUK7LhNlcg
          retries: 20
          wait: 16000
          sleep: 30000
